---
service: blog
schema_path: schemas
topics:
  - resource: post
    purpose: request
    properties:
      retry: true
      dlt: true
  - resource: post
    purpose: reply
    properties:
      retry: true
      dlt: true
  - resource: post
    purpose: event
    properties:
      retry: true
      dlt: true
